# Generated by Django 4.2.4 on 2023-11-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
