# Generated by Django 4.2.4 on 2023-11-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='song',
            new_name='singer',
        ),
    ]
